### PR TITLE
Decaffeinate `spec/apm-cli-spec`

### PR DESCRIPTION
**Pull request by GuilleW**
Merge https://github.com/pulsar-edit/ppm/pull/19 first.
EDIT : ❌ ~~[decaffeinate-project](https://decaffeinate-project.org) is used at first, then manual refactor/clean.~~

From coffee
```sh
$ jasmine-focused --captureExceptions --coffee spec/apm-cli-spec.coffee
> 6 tests, 24 assertions, 0 failures, 0 skipped
```
to js
```sh
$ jasmine-focused --captureExceptions spec/apm-cli-spec.js
> 6 tests, 24 assertions, 0 failures, 0 skipped
```

### CODE REVIEW

**Comment by GuilleW** [comment]
Following [@confused-Techie  comment](https://github.com/pulsar-edit/ppm/pull/15#issuecomment-1304931041), I forgot to follow [Decaffeination guidelines](https://github.com/pulsar-edit/.github/blob/main/project-birth/CONTRIBUTING-DURING-START.md#decaffeination).

## Steps to reproduce decaffeination:

- [x] Check package.json for coffee-script version
  - version: 1.12.7
- [x] Decaffeination with official Coffee program
  - `npx coffee --compile --output spec spec/apm-cli-spec.coffee`
- [x] Quality of Decaffeination
  - [x] Replace `var` with `const` and `let` if it's possible.
  - [x] Replace Nested [Ternary Operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) with if statements.
  - [x] Remove `return` when it's not needed.
  - [x] Remove Result Arrays when they are not needed.
  - [x] Replace for loops with [for-of loops](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of).
  - [x] Use [Arrow Functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) to write functions in a single line when it's possible.
  - [x] Remove unneeded ref variables.
  - [x] Remove [do blocks](https://devdocs.io/coffeescript~1/index#loops) and use let or const instead.
  - [x] Tests and assertions should be the same and success like in `coffee` file
  
## Should output same result :

From coffee
```sh
$ jasmine-focused --captureExceptions --coffee spec/apm-cli-spec.coffee
> 6 tests, 24 assertions, 0 failures, 0 skipped
```
to js
```sh
$ jasmine-focused --captureExceptions spec/apm-cli-spec.js
> 6 tests, 24 assertions, 0 failures, 0 skipped
```

**Review by Sertonix — APPROVED** [review]

**Review by confused-Techie — APPROVED** [review]
This PR looks fantastic, other than the lack of `;` which is just my preference and not at all needed to get the PR merged, I see no issues.

Fantastic work!

**Comment by 2colours** [comment]
Supposedly superseded by https://github.com/pulsar-edit/ppm/pull/64.

**Comment by confused-Techie** [comment]
Again @2colours has very helpful refactored this PR into the modern decaf format in #64 and that has now been merged.

Thanks a ton to @2colours & @GuilleW for all the hard work here

**Pull request closed without merging**
