### PR TITLE
Decaffeinate `spec/spec-helper` (Merge first: it's a dependency)

### PR DESCRIPTION
**Pull request by GuilleW**
Helper for unit test.
PR needed before other decaffeination in spec, because this file is included.
I don't remove `spec/spec-helper.coffee` actually, because it's useful during decaffeination.
⚠️ Should be removed at this end! ⚠️

### CODE REVIEW

**Comment by Sertonix** [comment]
You can remove the `.coffee` file in a commit but then restore it on your computer without committing it.

**Comment by GuilleW** [comment]
[decaffeinate-project](https://decaffeinate-project.org) is used at first, then manual refactor/clean.

**Review by Sertonix — APPROVED** [review]

**Review by GuilleW — COMMENTED** [review]
Can be merge 👍

**Review by confused-Techie — APPROVED** [review]
This PR looks fantastic, and I really do appreciate you linking and informing us about how the guide was used @GuilleW.

Thanks a ton for the contribution! 🎉

I'll go ahead and leave this up for a small time longer to ensure any other members are able to take a look otherwise I'll go ahead and merge it

**Comment by 2colours** [comment]
@confused-Techie Well well, it seems that the "small time" has passed. :)

Unfortunately, though, it cannot be merged immediately, since it needs to be consolidated with later changes... My idea would be to collect all changes to these coffee files, since the last commit of this branch, and integrate them into the js code as well. There cannot be that many changes. I can help if you wish.

**Comment by confused-Techie** [comment]
> @confused-Techie Well well, it seems that the "small time" has passed. :)
> 
> Unfortunately, though, it cannot be merged immediately, since it needs to be consolidated with later changes... My idea would be to collect all changes to these coffee files, since the last commit of this branch, and integrate them into the js code as well. There cannot be that many changes. I can help if you wish.

Yeah I'm sorry about that. If it's any consolation, your collection of PRs here helped us determine our proper workflow for decaf PRs, due to the difficulty in accurately reviewing them.

If willing any help would be awesome, but also if fine by you, I'd be willing to restructure these into our new workflow, so that they can finally be reviewed and merged.

Essentially what we have been doing going forward for any decaf work is this:

Firstly create a branch of **only** machine decaf files. 
Then from there have a second branch that does the work of decafing the files manually.
Finally make a PR of your `human-decaf` branch against the `machine-decaf` branch.

That way we are able to review what you specifically have done, without caring at all about the actual decaf, since we know the machine decaf will work.

Finally from there, once properly reviewed we can then merge it, but at the last second change the target branch to be the `main` branch.

But again, sorry for how long these have sat here untouched, if you're willing seeing this as a PR would be amazing, or if it's fine by you, I could do this with your changes, and attribute you as the author on the PRs

**Comment by 2colours** [comment]
This doesn't sound too bad. One can create a new machine-decaf branch from the current state of things, and then merge the updated version of this PR to that. What still needs to be kept in mind is that the main branch still needs to kept frozen, from the generation of the machine-decaf to the eventual merging of it.

I heard you had a discord server, let's talk about it there.

**Comment by 2colours** [comment]
Without further objections, this PR is superseded by https://github.com/pulsar-edit/ppm/pull/63.

**Comment by confused-Techie** [comment]
@2colours Has very helpfully refactored this PR into our modern Decaf process, and has kept your commits in their entirety, so this one has been merged, just on a different PR (#63 )

Thanks a ton to @2colours and @GuilleW for all the hard work here.

**Pull request closed without merging**
