### PR TITLE
Decaffeinate docs spec

### PR DESCRIPTION
**Pull request by 2colours**
Meant to supersede https://github.com/pulsar-edit/ppm/pull/27.
Again, it's almost verbatim because there have been no modifications upstream.
Otherwise, nothing unusual - less `function`s, and unused parameters might go with the underscore, linters tend to like that.

### CODE REVIEW

**Review by DeeDeeG — APPROVED** [review]
LGTM. Nice to get rid of all those not-helpful `return`s.

Again, I see no failures in CI.

As I commented in the other PR, I personally don't like losing all the blank lines between bits of code, but I'm waiting on a second opinion of another reviewer agreeing, so _please leave it as-is for now_, unless/until another reviewer says they agree with wanting to keep the blank lines.

**Review by confused-Techie — APPROVED** [review]
Fantastic PR, passing tests, super clean diff, and rad changes.

Do wanna say I appreciate making sure the respective `.coffee` file is getting deleted in these, that'll make things super easy to merge

**Review by DeeDeeG — APPROVED** [review]
👍

**Comment by DeeDeeG** [comment]
Some accidental stray spaces at the beginnings of lines were added. Gonna clean those up real quick.

**Pull request merged**
