### PR TITLE
Replace "apm" by "ppm" in help messages.

### PR DESCRIPTION
**Pull request by azuledu**
Replace all "apm" occurrences by "ppm" in console help messages.

### CODE REVIEW

**Comment by Daeraxa** [comment]
Seems good to me.

One note semi-related to this PR but not to be actioned on this is that we really need to decide which out of `ppm` or `pulsar -p` is the "primary" way of interacting with ppm.
For example if you run some of these commands running `pulsar -p` it seems odd that it returns instructions to use `ppm` instead.

**Comment by azuledu** [comment]
Maybe it is possible to substitute all "ppm" and "pulsar" occurrences in texts by a variable representing the script name. Something like `$0` in bash.

**Review by confused-Techie — APPROVED** [review]
LGTM! Thanks for doing this! And glad to see you contributing!

**Comment by DeeDeeG** [comment]
This makes me want to finally rename the actual binaries in this repo from `apm` to `ppm`.

But that is just another thing that's not meant to be part of this PR itself.

**Review by DeeDeeG — APPROVED** [review]
Looks Good To Me™️.

If no objections, I intend to merge this PR soon.

**Review by confused-Techie — APPROVED** [review]
This looks fantastic!
Thanks a ton for contributing and getting this done! Sorry it wasn't reviewed sooner

**Comment by confused-Techie** [comment]
@DeeDeeG Yeah that would be really awesome, and make things especially a little less weird on Windows as you can't use `pulsar -p`. So I'd be totally on board with that.

But with two approvals here, I'll merge this one

**Pull request merged**
